services:
  link_yeeter:
    container_name: link_yeeter
    restart: on-failure
    stop_signal: SIGINT
    build:
      context: .

    environment:
      RUST_LOG: none,link_yeeter=info # use "none,link_yeeter=debug" for debugging
      TELOXIDE_TOKEN: your-token
      ALLOWLIST: youtube.com,x.com
      MAX_FILESIZE: 200
      MAINTAINER: your-handle
